"use client";

/* Curated Lucide icon map. Only the icons used across the site are imported, so
   the bundle stays lean. Usage: <Icon name="shield-check" size={18} />. Icon
   names are the kebab-case Lucide names used in the design prototypes. */
import {
  Activity,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  BookOpen,
  BrainCircuit,
  Briefcase,
  CalendarCheck,
  Check,
  ChevronRight,
  CircleAlert,
  ClipboardCheck,
  Clock,
  Cloud,
  CloudUpload,
  Code,
  Compass,
  Database,
  FileCheck,
  FilePlus2,
  FileText,
  Fish,
  Folder,
  Gauge,
  GitBranch,
  GitFork,
  GraduationCap,
  Handshake,
  Image as ImageIcon,
  Headset,
  HeartHandshake,
  Info,
  Laptop,
  Layers,
  LayoutGrid,
  Library,
  LineChart,
  ListChecks,
  Lock,
  MailWarning,
  Mails,
  Map,
  MapPin,
  MessagesSquare,
  Package,
  Play,
  Presentation,
  Projector,
  Quote,
  Radar,
  Recycle,
  Route,
  Scale,
  Search,
  Server,
  Settings2,
  ShieldAlert,
  ShieldCheck,
  ShieldOff,
  ShieldX,
  Smartphone,
  Sparkles,
  Target,
  TrendingDown,
  TrendingUp,
  Truck,
  UserCheck,
  Users,
  Workflow,
  Wrench,
  Zap,
  type LucideProps,
} from "lucide-react";

const ICONS: Record<string, React.ComponentType<LucideProps>> = {
  "activity": Activity,
  "arrow-left": ArrowLeft,
  "arrow-left-right": ArrowLeftRight,
  "arrow-right": ArrowRight,
  "book-open": BookOpen,
  "brain-circuit": BrainCircuit,
  "briefcase": Briefcase,
  "calendar-check": CalendarCheck,
  "check": Check,
  "chevron-right": ChevronRight,
  "circle-alert": CircleAlert,
  "clipboard-check": ClipboardCheck,
  "clock": Clock,
  "cloud": Cloud,
  "cloud-upload": CloudUpload,
  "code": Code,
  "compass": Compass,
  "database": Database,
  "file-check": FileCheck,
  "file-plus-2": FilePlus2,
  "file-text": FileText,
  "fish": Fish,
  "folder": Folder,
  "gauge": Gauge,
  "git-branch": GitBranch,
  "git-fork": GitFork,
  "graduation-cap": GraduationCap,
  "handshake": Handshake,
  "image": ImageIcon,
  "headset": Headset,
  "heart-handshake": HeartHandshake,
  "info": Info,
  "laptop": Laptop,
  "layers": Layers,
  "layout-grid": LayoutGrid,
  "library": Library,
  "line-chart": LineChart,
  "list-checks": ListChecks,
  "lock": Lock,
  "mail-warning": MailWarning,
  "mails": Mails,
  "map": Map,
  "map-pin": MapPin,
  "messages-square": MessagesSquare,
  "package": Package,
  "play": Play,
  "presentation": Presentation,
  "projector": Projector,
  "quote": Quote,
  "radar": Radar,
  "recycle": Recycle,
  "route": Route,
  "scale": Scale,
  "search": Search,
  "server": Server,
  "settings-2": Settings2,
  "shield-alert": ShieldAlert,
  "shield-check": ShieldCheck,
  "shield-off": ShieldOff,
  "shield-x": ShieldX,
  "smartphone": Smartphone,
  "sparkles": Sparkles,
  "target": Target,
  "trending-down": TrendingDown,
  "trending-up": TrendingUp,
  "truck": Truck,
  "user-check": UserCheck,
  "users": Users,
  "workflow": Workflow,
  "wrench": Wrench,
  "zap": Zap,
};

export type IconName = keyof typeof ICONS;

export default function Icon({ name, ...props }: { name: string } & LucideProps) {
  const Cmp = ICONS[name];
  if (!Cmp) return null;
  return <Cmp {...props} />;
}
